version: "3.8"
   
services:
  db:
    build:
      context: ./.docker/postgres
    volumes:
      - ./.data/db:/var/lib/postgresql/data
      - ./.docker/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres